import {contextualFaqAnswer,type FaqContext} from './faq-context.ts';
import {matchFaq,type FaqTopic} from './faq.ts';
import {editingProducts,findProduct,productHref,productPrice,NODE_VIDEO_COMPATIBILITY,ACADEMY_URL} from './editing-products.ts';
import type {PortfolioData} from './types';
export const JORAK_YOUTUBE_URL='https://www.youtube.com/channel/UCF-jHvQ-q1N-zLheeUQRVcw';
const normalize=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
type Answer={answer:string;href:string;label:string};
export function answerFaqQuestion(question:string,data:PortfolioData,context:FaqContext,previousQuestions:string[]=[],classifiedTopic?:FaqTopic):Answer{
  const recent=previousQuestions.slice(-6),raw=normalize(question);
  const followUp=/^(e |mas |pode explicar|explique|mais detalhes|como assim|nao entendi|e isso)/.test(raw);
  // History carries questions only. It never supplies facts, prices or form values.
  const text=followUp&&/^(pode explicar|explique|mais detalhes|como assim|nao entendi|e isso)/.test(raw)?normalize(recent.at(-1)||question):raw;
  const repeat=recent.filter(value=>normalize(value)===text).length;
  const product=context.page==='product-contact'?findProduct(context.productId):undefined;
  const result=(first:string,detail:string,href:string,label:string):Answer=>({answer:repeat||followUp?detail:first,href,label});
  const catalog='/projetos-de-edicao',collection='/?visao=todos';
  if(/obrigad|valeu/.test(text))return result('Por nada! Se surgir outra dúvida, pode perguntar.','À disposição. Você pode continuar explorando e me chamar quando precisar.',collection,'Voltar à coleção');
  if(/^(oi|ola|bom dia|boa tarde|boa noite)[!?. ]*$/.test(text))return result('Olá! Qual dúvida você quer esclarecer nesta página?','Oi de novo! Escreva sua pergunta ou escolha uma sugestão abaixo.',collection,'Explore os trabalhos');
  if(/compatib|versao|6[.,]70/.test(text))return result(NODE_VIDEO_COMPATIBILITY+' A versão 6.70 não está incluída.','Para abrir o arquivo, use uma versão do Node Video acima de 6.70. A própria 6.70 e as anteriores ficam fora da compatibilidade informada.',product?productHref(product):catalog,'Ver projeto para Node Video');
  if(product&&/preco|valor|custa|quanto|selecionei|qual projeto/.test(text))return result(`Você selecionou ${product.name}, de ${product.artist}, por ${productPrice(product)}. O valor deste arquivo é fixo.`,`Nesta solicitação, o arquivo é ${product.name} (${product.artist}). O preço continua sendo ${productPrice(product)}; ele vem do catálogo e não pode ser alterado no formulário.`,productHref(product),'Ver esta solicitação');
  if(product&&/enviar|interesse|formulario|comprar|pagamento/.test(text))return result('Preencha nome, e-mail e mensagem e pressione “Enviar interesse neste projeto”. A solicitação será registrada para contato; esta página não realiza pagamento.','Conte na mensagem que deseja este arquivo e use um e-mail pelo qual possa receber retorno. Após enviar, aguarde a confirmação na página. Produto e preço já vêm definidos pelo catálogo.',productHref(product),'Enviar meu interesse');
  if(/licenca|suporte|reembolso|vitalici|garantia/.test(text))return result('As condições de licença, suporte e reembolso não estão cadastradas. Confirme essas condições diretamente com Jorak antes de adquirir um arquivo.','Não há informação confirmada para essa condição no catálogo. Inclua sua dúvida na mensagem de interesse para que Jorak esclareça antes da aquisição.',product?productHref(product):'/contato','Consultar condições');
  if(/gratuito|cristino|download|baixar/.test(text)){
    const free=editingProducts.find(item=>item.price===0)!;
    return result('Cristino (Shiny) é o projeto gratuito. No catálogo, o botão desse arquivo abre o link de download publicado. Os demais projetos possuem preço e solicitação de interesse.','Abra Projetos de edição e localize Cristino, de Shiny. Use o download gratuito indicado no cartão; isso não exige uma solicitação de compra.',productHref(free),'Download gratuito de Cristino');
  }
  if(context.page==='academy'){
    if(/site|link|acessar|endereco/.test(text))return result(`O site oficial da Surfate Academy é ${ACADEMY_URL}. Você pode acessá-lo pelo botão abaixo.`,'O botão abaixo abre o site oficial da Surfate Academy em outra página, com as informações publicadas pela própria equipe.',ACADEMY_URL,'Site oficial da academia');
    if(/relacao|professor|jorak|equipe/.test(text))return result('Jorak integra a equipe da Surfate Academy como professor de animação 2D no celular. Essa é a atuação apresentada no portfólio.','Na academia, a participação registrada de Jorak é no ensino de animação 2D pelo celular. Para conhecer a proposta da equipe, consulte o site oficial.',ACADEMY_URL,'Conhecer a academia');
    return result('O portfólio confirma a atuação de Jorak como professor de animação 2D no celular. Programa, preços, duração e vagas devem ser consultados no site oficial da Surfate Academy.','Não há uma grade completa ou oferta de matrícula cadastrada aqui. A fonte para os detalhes atuais da formação é o site da própria Surfate Academy.',ACADEMY_URL,'Consultar a formação');
  }
  if(/filtr|por artista/.test(text))return result('Selecione “Por artista” e escolha o colaborador desejado. A coleção exibirá os trabalhos associados a ele. Use “Todos” para voltar à coleção completa.','O filtro usa o artista do catálogo. Escolha outro nome para trocar a seleção; para explorar sem restringir artistas, retorne a Todos.',collection,'Explorar por artista');
  if(/buscar|busca|pesquis|encontrar/.test(text))return result('Abra o Índice e digite o nome da música, personagem ou artista no campo de busca. Selecione um resultado para abrir o projeto.','No Índice, a busca combina música, personagem e artista. Se não encontrar o trabalho, reduza o texto digitado e limpe os filtros ativos.', '/?indice=1','Abrir índice');
  if(/quantos|quantas|numero|total/.test(text)&&/trabalh|projet|colecao/.test(text))return result(`A coleção pública tem ${data.projects.length} trabalhos com recortes disponíveis da participação de Jorak. Use Todos para consultá-los.`,`São ${data.projects.length} trabalhos disponíveis nesta coleção. O catálogo de arquivos para Node Video é separado e pode incluir outros projetos.`,collection,'Ver todos os trabalhos');
  if(/disco|explor|navega|setas|arrast/.test(text))return result('Arraste os discos ou use as setas para selecionar um trabalho. Clique no disco escolhido para abrir a prévia e depois em “Abrir projeto completo” para ver os detalhes.','Você também pode usar o teclado para selecionar os discos e Enter para abrir a prévia. Todos mostra a coleção completa; Por artista restringe a seleção a um colaborador.',collection,'Explorar os discos');
  if(/referencia/.test(text))return result('Envie links de vídeos que expressem o ritmo, o estilo visual ou o tipo de movimento que você procura. Explique o que deseja aproveitar em cada referência.','Uma referência fica mais útil quando você indica o trecho e o motivo: cortes, cores, animação, tipografia ou ritmo. Inclua os links na descrição do formulário, junto da sua ideia.','/contato','Enviar referências');
  if(/formulario|preencher|enviar.*(pedido|mensagem)/.test(text)&&!product)return result('Preencha nome, e-mail, tipo de edição e descrição da ideia no formulário Vamos criar. Inclua duração e prazo desejado. Depois do envio, a página confirma o registro.','Use um e-mail para retorno e descreva o resultado que espera, o material disponível e suas referências. Os campos do formulário não são lidos por esta conversa.','/contato','Abrir formulário');
  if(/canal|youtube/.test(text)&&context.page==='about')return result('O canal do Jorak no YouTube reúne publicações do próprio editor. O link também está em Sobre mim.','Para ver as publicações do editor, abra o canal oficial do Jorak pelo link abaixo.',JORAK_YOUTUBE_URL,'Canal do Jorak');
  if(context.page==='products'&&/consultar|pago|interesse|comprar/.test(text))return result('Escolha o cartão do projeto pago e abra sua solicitação de interesse. Cada arquivo possui página própria com nome, artista e preço fixo.','No catálogo, selecione o arquivo que deseja. A página seguinte mantém esse produto e preço definidos; você só informa nome, e-mail e mensagem.',catalog,'Escolher um projeto');
  const topic=classifiedTopic||matchFaq(question);
  if(topic==='artists'){
    const artist=data.artists.find(item=>text.includes(normalize(item.name)));
    if(artist){const projects=data.projects.filter(item=>item.artistIds?.includes(artist.id));return result(`O catálogo reúne ${projects.length} trabalhos com ${artist.name}. Selecione esse artista no filtro para explorar as colaborações.`,`Para consultar as edições com ${artist.name}, abra Todos e use Por artista. Cada página traz os créditos e o lançamento original.`,collection,'Ver colaborações');}
  }
  if(topic==='identity')return result(data.settings?.bio||'Jorak é editor MMV e motion designer da cena geek brasileira. Sua trajetória está na página Sobre mim.',data.settings?.career||'A apresentação e a trajetória publicadas pelo editor estão em Sobre mim. Você também encontra lá o canal do Jorak e seus trabalhos.','/sobre','Sobre mim');
  if(topic==='budget')return result('Edições personalizadas não têm preço fixo cadastrado. Envie sua ideia, duração, referências e prazo desejado; o orçamento será combinado diretamente.','O custo de uma edição depende do escopo que você apresentar. Os valores do catálogo são para arquivos de projeto e não são uma tabela de preços para contratar um vídeo novo.','/contato','Solicitar orçamento');
  if(topic==='deadline')return result('Prazo e disponibilidade precisam ser confirmados diretamente com Jorak. Informe a data desejada e o escopo no contato.','A data que você informar é uma preferência para avaliação, não uma entrega confirmada. Jorak precisa avaliar o trabalho antes de combinar um prazo.','/contato','Consultar prazo');
  if(topic==='tools')return result('As ferramentas confirmadas aparecem nos detalhes de cada trabalho. Os arquivos à venda neste catálogo são para Node Video.','Consulte a página do projeto para verificar as ferramentas usadas naquela edição. Não há uma lista única de programas que se aplique a todos os trabalhos.',collection,'Consultar ferramentas');
  if(topic==='unknown')return result('Não encontrei essa informação no conteúdo confirmado do portfólio. Pode dizer se sua dúvida é sobre um trabalho, arquivo de projeto, academia ou contato?','Ainda falta uma informação confirmada para responder a essa dúvida. Você pode reformular a pergunta com o nome do trabalho ou encaminhá-la diretamente a Jorak.','/contato','Falar com Jorak');

  if(topic==='services')return result('Jorak trabalha com edição de videoclipes/MMV, trailers e motion design. Para um pedido, indique o formato e o tipo de resultado que procura.','Videoclipes/MMV combinam cenas e ritmo musical; trailers apresentam um trabalho em um trecho curto; motion design envolve animação de elementos visuais. O escopo será definido com sua ideia.','/contato','Apresentar minha ideia');
  if(topic==='contact')return result('Use Vamos criar para falar diretamente com Jorak. Informe seu e-mail e conte o que deseja produzir.','A solicitação é enviada pelo formulário de contato. Inclua a ideia e um e-mail para retorno; seus dados preenchidos não são usados pelo FAQ.','/contato','Vamos criar');
  const fallback=contextualFaqAnswer(topic,data,context);
  return repeat?{...fallback,answer:`Sobre essa dúvida, a informação confirmada continua sendo: ${fallback.answer}`}:fallback;
}
